/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flashloanArbitrageBotSol from "./FlashloanArbitrageBot.sol";
export type { flashloanArbitrageBotSol };
